{code lang=kt}
fun foo(x: String): String {
    try {
        throw RuntimeException()
    } finally {
        try {
        } catch (e: Exception) {
        }
        return x     // <- Wrong UNREACHABLE_CODE
    }
}
{code}
(If you remove the try-catch statement, the error disappears)