This exception occurs quite often (about 10 reports per day), and it's not very obvious how to fix it. From the other side, this `assertValid` check can provoke exceptions in situation when we are able to return correct result. To be discussed before 1.2 release.