Inner call with type parameter inferred to error type leads to additional errors.
Without intermediate calls in all branches error is not reported on special constructions.
```
import java.lang.Exception

fun <K> id(arg: K): K = arg

fun test() {
    id(unresolved)!!
    unresolved!!!!
    try {
        id(unresolved)
    } catch (e: Exception) {
        id(unresolved)
    }

    if (true)
        id(unresolved)
    else
        id(unresolved)

    when {
        true -> id(unresolved)
    }
    id(unresolved) ?: id(unresolved)
}
```

Plugin version: 1.4.0-dev-1075-IJ2019.3-1