The code is:
```
class Foo<T>
class Bar<S>

fun <T> consume(x: Foo<out T>, y: Foo<out T>) {}
fun <T> materialize() = null as T

fun test() = consume(
    materialize<Foo<Bar<ErrorType>>>(),
    materialize<Foo<Bar<ErrorType>>>()
)
```

This problem can be important when kapt, for example, is used: "generate stubs" task might stumble upon such exception, and then compilation as a whole will fail.