```kotlin
var foo = 1
try {
	foo = 2 // WARNING: The value '2' assigned to 'var foo: kotlin.Int defined in foo.main' is never used
	throw RuntimeException()
} catch (e: Throwable) {
	println(foo)
}
```

Here should be no warning.