{code}
fun foo() {
    try {
    } catch (e: Exception = java.lang.RuntimeException("")) {
    }
}
{code}