Found by @hepin1989.

```scala
try { 1 } catch { 
  case _: Exception ⇒ println("Something went wrong")
  case ex: IllegalArgumentException ⇒ println(ex.getMessage)
}
```
Doesn't print a warning.

```scala
(new IllegalArgumentException()) match { 
  case _: Exception ⇒ println("Something went wrong")
  case ex: IllegalArgumentException ⇒ println(ex.getMessage)
}
```
Does.