Originally reported in GRECLIPSE-1588, it seems like {{org.codehaus.groovy.transform.stc.GroovyTypeCheckingExtensionSupport.safeCall(Closure, Object...)}} is not all that safe.  There is a catch block, but it only catches {{InvokerInvocationException}}s.  If the DSL script throws any other kind of exception, the problem bubbles up and eventually crashes the compiler (or at least produces some obtuse errors.

Suggestion:

Change the catch block from catching {{InvokerInvocationException}} to {{Exception}}.